# Generated by Django 4.0.6 on 2022-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0013_strategy_shift_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='squareoff_request',
            field=models.CharField(default='nothing', max_length=10),
        ),
    ]
