# Generated by Django 4.2.6 on 2023-10-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0014_strategy_squareoff_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('paraphrase', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='positions',
            old_name='side',
            new_name='order_type',
        ),
        migrations.RenameField(
            model_name='positions',
            old_name='current_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='positions',
            old_name='time_in',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='lots',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='pnl',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='price_in',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='price_out',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='status',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='time_out',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='token',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='bots_started',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='monthly_expiry',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='shift_position',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='squareoff_request',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='weekly_expiry',
        ),
        migrations.AlterField(
            model_name='strategy',
            name='bot',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='paper',
            field=models.BooleanField(default=False),
        ),
    ]
