# Generated by Django 4.2.6 on 2023-10-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0015_admin_rename_side_positions_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='expiry_date',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
