# Generated by Django 4.2.7 on 2023-11-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0018_delete_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='oanda_account_id',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
