# Generated by Django 4.2.7 on 2023-12-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0020_admin_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Live',
            field=models.BooleanField(default=True),
        ),
    ]
